using System;
using System.Collections.Generic;

//The sequence of triangle numbers is generated by adding the natural numbers.So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

//1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

//Let us list the factors of the first seven triangle numbers:

// 1: 1
// 3: 1,3
// 6: 1,2,3,6
//10: 1,2,5,10
//15: 1,3,5,15
//21: 1,3,7,21
//28: 1,2,4,7,14,28
//We can see that 28 is the first triangle number to have over five divisors.

//What is the value of the first triangle number to have over five hundred divisors?

//Rule: <Triangle of n> = n(n+1)/2

namespace HighlyDivisiblyTriangular
{
    class Program
    {
        static void Main(string[] args)
        {
            const long numDivisors = 500;

            try
            {
                for (long i = 1; ; i++)
                {
                    long tri = GetTriangular(i);
                    int countDivisors = 0;
                    long end = (int)Math.Sqrt(tri);

                    for (int j = 1; j < end; j++)
                    {
                        // Have we got a factor?
                        if (tri % j == 0)
                            countDivisors += 2;
                    }

                    if (end * end == i)
                        countDivisors++;

                    // Have we got > the specified number of divisors?
                    if (countDivisors > numDivisors)
                    {
                        Console.WriteLine("Answer = " + tri);
                        break;
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("The following error occurred: " + e.Message + " : " + e.InnerException);

            }
        }

        static long GetTriangular(long n)
        {
            //Rule: <Triangle of n> = n(n+1)/2
            long value = 0;

            value = ( n *(n + 1) )/ 2;
            return value;
        }
    }
}
